### ISSUE TITLE
Migration from Mandrill to Sendgrid.

### ISSUE THREAD

**Issue by fluffywaffles** [NUisEPIC/formula-one#1]
confirmation-mailer and mailer.js need to be updated to use the correct API.

**Comment by murfalo** [comment]
This is basically done except that we haven't merged the branch with master... should we go ahead and do that?  Also, let me know when you're ready to continue working on this project and finish getting it prepared for fall recruitment!

**Comment by fluffywaffles** [comment]
@Murfalo Hey! Yeah, let's do that. Hit me up on some other medium and we can figure out a time to talk about what needs to get done.
