### ISSUE TITLE
Leave Bower

### ISSUE THREAD

**Issue by fluffywaffles** [NUisEPIC/formula-one#2]
Stop using bower for package management

**Comment by itsmichaelwang** [comment]
what's wrong with bower

**Comment by itsmichaelwang** [comment]
LEAVE BOWER ALONE
![bower-bully](http://d3lp4xedbqa8a5.cloudfront.net/s3/digital-cougar-assets/WomansDay/2016/02/24/14762/Chris-Crocker-main.jpg?width=690&height=&mode=crop&quality=75)

**Comment by fluffywaffles** [comment]
It's redundant because you can load front-end packages from npm.

**Comment by fluffywaffles** [comment]
Done.
