### ISSUE TITLE
Better Authentication

### ISSUE THREAD

**Issue by fluffywaffles** [NUisEPIC/formula-one#5]
Using node-jsonwebtoken
And with a simple middleware for verification
And with a simple endpoint for authentication
eg

POST /authenticate => a JWT

every other request requires that your JWT is included in the Authorization header, which is enforced using middleware and jwt.verify.

**Comment by murfalo** [comment]
Going ahead and closing this

**Comment by fluffywaffles** [comment]
:+1:
